name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
          
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools pybind11-stubgen

    - name: Build and install
      run: pip install --verbose .[test]
      env:
        CC:  clang-12
        CXX: clang++-12

    - name: Generate stubs
      run: |
        cd ./build/lib.*
        pybind11-stubgen craftcpp --no-setup-py --output-dir="."
        mv ./*-stubs/__init__.pyi ./craftcpp.pyi
      env:
        PYTHONPATH: .
        PYTHONUTF8: 1

    - name: Move artifact
      run: |
        mkdir artifact
        mv ./build/lib.*/* ./artifact

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: craftcpp
        path: artifact/*