name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10"]
          
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools pybind11-stubgen pytest

    - name: Build
      run: python setup.py bdist_wheel
      env:
        CC:  clang-12
        CXX: clang++-12
        PYTHONUTF8: 1

    - name: Test
      run: python -m pytest
      working-directory: ../
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: craftcpp
        path: dist/*

  upload-wheel:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
          name: craftcpp
          path: dist
    
    - name: Publish package to Private Repository
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: ${{ secrets.PYPI_USER }}
        password: ${{ secrets.PYPI_PASSWORD }}
        repository_url: ${{ secrets.PYPI_URL }}